BEGIN;

DROP SCHEMA IF EXISTS public CASCADE;

CREATE SCHEMA public;

CREATE TABLE public.exams(
id SERIAL PRIMARY KEY,
examid VARCHAR(255) NOT NULL,
examname VARCHAR(255) NOT NULL,
createddate DATE NOT NULL,
createdby VARCHAR(255) NOT NULL,
updateddate DATE NOT NULL,
updatedby VARCHAR(255) NOT NULL,
);

COMMIT;
